[workspace]
members = ["./crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97.1"
license = "MIT"
readme = "README.md"
repository = "https://github.com/matharts/ziwei"

[workspace.dependencies]
allocation-counter = "0.8.1"
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support"] }
ziwei = { path = "crates/ziwei" }
ziwei_analysis = { path = "crates/ziwei_analysis" }
ziwei_calendar = { path = "crates/ziwei_calendar" }
ziwei_core = { path = "crates/ziwei_core" }
ziwei_query = { path = "crates/ziwei_query" }

[workspace.lints.rust]
missing_docs = "warn"
