packages:
  - apps/*
  - packages/*
  - tools/*
  - "!**/test/**"
allowBuilds:
  lefthook: true

catalog:
  "@moonrepo/cli": 2.3.4
  "@vitest/coverage-v8": 4.1.9
  "@types/node": 25.9.4
  "@typescript/native-preview": 7.0.0-dev.20260624.1
  "@changesets/cli": 3.0.0-next.5
  "@changesets/types": 6.1.0
  vite: 8.1.0
  vitest: 4.1.9
  lefthook: 2.1.9
  oxfmt: 0.56.0
  oxlint: 1.71.0
  oxlint-tsgolint: 0.23.0
  tsdown: 0.22.3
  typescript: 6.0.3
  publint: 0.3.21

minimumReleaseAge: 0
