layer: "library"
language: "typescript"

project:
  name: "chart"
  description: "A repo management tool."
  owner: "lzm0x219"
  maintainers: ["lzm0x219"]

tasks:
  build:
    command: "tsdown"
    inputs:
      - "@globs(sources)"
      - "tsdown.config.ts"
    outputs:
      - "dist"
