export default function NatalChart() {
  return (
    <svg viewBox="0 0 865 865">
      <rect
        x="20"
        y="20"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="120"
        y="20"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="220"
        y="20"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="320"
        y="20"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="320"
        y="120"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="320"
        y="220"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="320"
        y="320"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="220"
        y="320"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="120"
        y="320"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="20"
        y="320"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="20"
        y="120"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <rect
        x="20"
        y="220"
        width="100"
        height="100"
        fill="white"
        stroke="black"
        strokeWidth="2"
      />
      <text x="40" y="40">
        Hello
      </text>
    </svg>
  );
}
