# yaml-language-server: $schema=../cache/schemas/tasks.json

fileGroups:
  configs:
    - "*.config.{js,cjs,mjs}"
    - "*.json"
  sources:
    - "src/**/*"
    - "types/**/*"
  tests:
    - "tests/**/*"
    - "**/__tests__/**/*"
  assets:
    - "assets/**/*"
    - "images/**/*"
    - "static/**/*"
    - "**/*.{scss,css}"

implicitDeps:
  - "^:build"
